# Generated by Django 3.0.5 on 2020-04-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('creation', models.DateTimeField(verbose_name='Timestamp of bug report')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-status', '-creation'],
            },
        ),
        migrations.CreateModel(
            name='ChronicleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('creation', models.DateTimeField(verbose_name='Timestamp of project creation')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_creator', to='chronicles_backend.ChronicleUser')),
                ('team', models.ManyToManyField(related_name='Project_team', to='chronicles_backend.ChronicleUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(verbose_name='Timestamp of comment')),
                ('body', models.CharField(max_length=1000)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chronicles_backend.ChronicleUser')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicles_backend.BugReport')),
            ],
            options={
                'ordering': ['-creation'],
            },
        ),
        migrations.AddField(
            model_name='bugreport',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BugReport_pic', to='chronicles_backend.ChronicleUser'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicles_backend.Project'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BugReport_reporter', to='chronicles_backend.ChronicleUser'),
        ),
    ]
