# Generated by Django 3.0.5 on 2020-06-16 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 16, 13, 24, 995975), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 16, 13, 24, 996620), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 16, 13, 24, 993919), verbose_name='Timestamp of project creation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='defaults/ProjectLogo.png', upload_to='projectImages/'),
        ),
    ]
