# Generated by Django 3.0.5 on 2020-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicleuser',
            name='role',
        ),
        migrations.AddField(
            model_name='chronicleuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
