# Generated by Django 3.0.5 on 2020-05-01 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 12, 13, 30, 423071), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 12, 13, 30, 419512), verbose_name='Timestamp of project creation'),
        ),
    ]
