# Generated by Django 3.0.5 on 2020-05-02 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='tagsHash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 20, 17, 45, 442716), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 20, 17, 45, 443117), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 20, 17, 45, 441972), verbose_name='Timestamp of project creation'),
        ),
    ]
