# Generated by Django 3.0.5 on 2020-05-27 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 17, 19, 16, 199711), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 17, 19, 16, 200361), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 17, 19, 16, 198692), verbose_name='Timestamp of project creation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
