# Generated by Django 3.0.5 on 2020-04-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0002_auto_20200429_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to='chronicles_backend.ChronicleUser'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to='chronicles_backend.ChronicleUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='chronicles_backend.ChronicleUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='chronicles_backend.ChronicleUser'),
        ),
    ]
