# Generated by Django 3.0.5 on 2020-04-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0003_auto_20200429_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_assigned', to='chronicles_backend.ChronicleUser'),
        ),
    ]
