# Generated by Django 3.0.5 on 2020-06-07 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0003_auto_20200607_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 19, 25, 15, 209745), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 19, 25, 15, 211598), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 19, 25, 15, 203649), verbose_name='Timestamp of project creation'),
        ),
    ]
