# Generated by Django 3.0.5 on 2020-05-30 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0004_auto_20200530_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ['status', 'creation']},
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 44, 26, 501789), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 44, 26, 502404), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 44, 26, 500895), verbose_name='Timestamp of project creation'),
        ),
    ]
