# Generated by Django 3.0.5 on 2020-06-08 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0004_auto_20200607_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 32, 32, 827578), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 32, 32, 827988), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 32, 32, 826164), verbose_name='Timestamp of project creation'),
        ),
    ]
