# Generated by Django 3.0.5 on 2020-06-07 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0007_auto_20200605_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.CharField(default='itstheslug', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 13, 39, 246150), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 13, 39, 247229), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 13, 39, 244751), verbose_name='Timestamp of project creation'),
        ),
    ]
