# Generated by Django 3.0.5 on 2020-06-11 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0007_auto_20200611_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 18, 25, 4, 787043), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='chronicleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 18, 25, 4, 787469), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 18, 25, 4, 785619), verbose_name='Timestamp of project creation'),
        ),
    ]
