# Generated by Django 3.0.5 on 2020-06-07 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles_backend', '0008_auto_20200607_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='slug',
            new_name='randIdentifier',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 26, 49, 71487), verbose_name='Timestamp of bug report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 26, 49, 73301), verbose_name='Timestamp of comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 26, 49, 68251), verbose_name='Timestamp of project creation'),
        ),
    ]
