DEBUG: TRUE
SECRET_KEY: # YOUR_SECRET_KEY

CHANNELI:
  CLIENT_ID: # CLIENT ID FOR CHANNELI OAUTH
  CLIENT_SECRET: # CLIENT SECRET FOR CHANNELI OAUTH
  REDIRECT_URI: # REDIRECT URI

FRONTEND: # URL (FRONTEND)

EMAIL:
  ADDRESS: # MAILING ADDRESS
  PASSWORD: # PASSWORD FOR THE ABOVE ADDRESS

# DO NOT CHANGE THE CONFIGURATIONS BELOW
DATABASE:
  HOST: db 
  PORT: 5432
  NAME: chroniclesdb
  USER: chronicles
  PASSWORD: chronicles

ALLOWED_HOSTS:
  - "web"
  - "localhost"
  - "127.0.0.1"

CHANNEL_LAYER:
  HOST: 'redis'
  PORT: '6379'
